### ISSUE TITLE
Probing settings won't update any more

### ISSUE THREAD

**Issue by tmenet** [Sienci-Labs/gsender#135]
Looking at the settings for Probe I noticed you supported Z only probes for touchplate type. So I changed type to Z probe. That change worked fine. Then I decided to change my slow find to 25 mm/min and my retraction to 2 mm.

I tried to perform the probing operation and I noticed that it still behaved the same. Went back to my probe settings and the values had reverted back to initial values with a slow find of 75 mm/min and retraction of 4 mm.

After several attempts to change with no luck I decided I would try going back to "Standard Block" touchplate type. So then it got stuck on Z probe even though the graphics for the probe show a touchplate. After fiddling around it finally changed to standard block and I cannot get it to change back to Z probe type. Not sure what I did differently.

So with all the strange issues I can always change the Z-thickness and the change always takes hold and works fine. I really like the connectivity test.  

I looked but I did not see this as a reported issue.

**Comment by kglovern** [comment]
This should be fixed in 1.1.4.  Thanks for the report.
