### ISSUE TITLE
Verion 1.1.6 xyz probe causes Z to go crash down at the end

### ISSUE THREAD

**Issue by tmenet** [Sienci-Labs/gsender#186]
Crazy movement at the end of a probing cycle. Z alone works fine. XY probing  cause gantry to crash in positive x direction. XYZ cause  Z to crash towards probe (down) at he end. If end limits are set you jest get an error at the end.

**Comment by kglovern** [comment]
Hi @tmenet - could you look at your EEPROM settings and let me know if $13 is enabled?  If it is, disable it and let me know if you see the same behaviour.  We found a missing unit modal in the probe code and want to verify that fix.

**Comment by tmenet** [comment]
$13 was not enabled. (set to mm) I enabled it ( inches) and the problem went away. So yes, you are on to the fix. Thank you!

**Comment by kglovern** [comment]
This should be fixed in 1.1.7.  Make sure to remember to turn off $13 if you don't need it enabled (you definitely don't).
