### ISSUE TITLE
Resume job at line assumes 'zMax + 10' is valid

### ISSUE THREAD

**Issue by coffeecop** [Sienci-Labs/gsender#240]
When resuming a job the gcode:start command assumes that 'zMax + 10' is a valid position. If the zMax of your job is within 10 units of your zLimit 'resume from line' will either hit your hard-limit if enabled, or cam-out and your Z axis will be off by '10 - (zLimit - zMax)' for the remainder of the job.

https://github.com/Sienci-Labs/gsender/blob/master/src/server/controllers/Grbl/GrblController.js#L1290

**Comment by kglovern** [comment]
Thanks for the report.  We've kept the default Z movement as 10, but this is now configurable in the start from line modal before running.  This will be in an upcoming release.
