### ISSUE TITLE
Allow negative laser offset

### ISSUE THREAD

**Issue by gcormier** [Sienci-Labs/gsender#250]
For those of us with a laser mounted in such a configuration, please allow a negative laser offset. Right now gSender strips the negative sign in latest edge.

**Comment by kglovern** [comment]
Which version are you using?  There is a regression in Edge that we'll get fixed, but it's working fine in 1.1.7/main release.

**Comment by gcormier** [comment]
Now that you mention it... it worked fine in stable; it was only edge that didn't allow it. Thanks!
