### ISSUE TITLE
Thunder connections .... don't use them

### ISSUE THREAD

**Issue by LaserGrunt** [Sienci-Labs/gsender#253]
I have discovered that on both regular and edge that when I turn the coolant and spindle on g-sender will lose connection with the machine and the IOT relay will not turn off. Coming the power source from the control board and all other parts of the LongMill does not fix this. The issue will still be presented when power is applied.

-solution : when you unplug the USB-C from the thunder connector the IOT relay will turn off..... Only use regular USB-C ports on Macs

**Comment by jdforsythe** [comment]
@Modern-Memories I have a Macbook Pro that only has the Thunderbolt ports and haven't experienced this, but I only use it with a USB-C 4 port hub, so maybe that's why.
