### ISSUE TITLE
 gSender missing feature - “Probe Distance” 

### ISSUE THREAD

**Issue by dlpgraphics** [Sienci-Labs/gsender#255]
Coming from gSender from UGS I really miss the ability to input the Probe Distance. This is a continuous issue for me. I am using gSender with a CNC4Nebie HSNC4836 machine. It has limit switch at the top of Z axis . Total z travel is 175mm. If I am probing anything below -157mm it gives me soft limit alarm. I have to disable soft limits to probe my spoilboard. Once a machine is set up there should be no reason to bypass soft limits. I like the gSender interface but this is close to a deal breaker for me. Please add adjustable Probe Distance setting like UGS does it.

**Comment by kglovern** [comment]
This feature is available on our test platform (Edge) and will be part of the next main release (1.2.0)
