### ISSUE TITLE
Bug: Tool Change Issue Crash on multiple attempts -- v1.2.3-EDGE

### ISSUE THREAD

**Issue by majerus1223** [Sienci-Labs/gsender#276]
When the tool change command is detected, you are promoted to save positions via a dialog. This works the first time, however if you run another job, with the same configuration and attempt another tool change the dialog closes completely. 

v1.2.3-EDGE -- Windows 10 tried on 2 machines

**Comment by majerus1223** [comment]
One other addtional thing I noticed. Within the UI there is a reference to "PH" what does this mean? Is this expected, if not can it be changed to something more human? 
![Snag_38d65938](https://user-images.githubusercontent.com/7389171/218558248-4678170a-ba58-4cb2-a1d6-0d9b2e4f2366.png)

**Comment by kglovern** [comment]
We'll take a look at the issue with multiple toolchanges.

PH is placeholder.  Since Edge is the beta equivalent version not everything is final including text/labels.  It will be a more human copy by final release.

**Comment by kglovern** [comment]
Crashing on subsequent tool changes should have been fixed in the latest edge release
