### ISSUE TITLE
Compatibility with grblHAL

### ISSUE THREAD

**Issue by tetref** [Sienci-Labs/gsender#289]
Do you plan to make this software compatible with a modern version grblHAL? I couldn't connect with my STM32 Blackpill, it's the only software that doesn't work for me with grblHAL. It doesn't even have the CNCjs problem, although it's not fully compatible.

**Comment by kglovern** [comment]
We are actually working on supporting other firmware, with grblHal being the first secondary firmware supported.  No timeline yet, but it's in progress.
