### ISSUE TITLE
Settings/Shortcuts [Print]

### ISSUE THREAD

**Issue by GoranP-se** [Sienci-Labs/gsender#298]
In the Settings/Shortcuts formular is in top a blue button with **Print** text in. What is the purpose with this? Nothing happens when I press it, _(it seems to have a toogle function)_.
My wish is that if I press this one, I have the possibility to print out on paper my actual shortcut settings..

**Comment by kglovern** [comment]
This is in 1.2.4-EDGE?  We'll take a look - it should print out a copy of the currently set keybinds

**Comment by kglovern** [comment]
This will be fixed in an upcoming release, thanks for the report!
