### ISSUE TITLE
Feature request - start GCode for resuming from specific line

### ISSUE THREAD

**Issue by jdforsythe** [Sienci-Labs/gsender#300]
I use the Digital Loggers IOT relay and have start/stop GCode to turn it on and off. However, the start GCode is not run when I resume a file from a particular line. So if I pause a job and come back later, I have to remember to manually click coolant flood and turn on the laser/router before clicking start.

If it's a laser project, it's not a huge deal unless I didn't write down which line I needed to start from, because I need to restart it again. If it's a CNC project, that could mean the bit starts dragging across or running into a work piece, ruining it. Normally it takes a second after I click start to hear the click and then my pause message comes up, but I started from a specific line and it caught me by surprise and immediately started dragging the bit across the surface.

It would be great to have start GCode that would run only when resuming from a specific line, or at least a checkbox in the "run from line number" dialog to run the start GCode before resuming.

**Comment by kglovern** [comment]
This is implemented internally and will be in the next major release.
