### ISSUE TITLE
Feature Request - Quick Go To coordinates or offset

### ISSUE THREAD

**Issue by jdforsythe** [Sienci-Labs/gsender#304]
There are times I want to travel to a specific set of coordinates or travel some specific distance offset from current position. This can of course be achieved through the console, but having a button to open a dialog to type the numbers in would be more user-friendly.

Two example use cases:

With the Longmill MK2 laser kit, the laser as it is mounted on my machine is 2.597" in front of the spindle center. So to line things up with the grid I cut into my spoilboard, I need to home the machine and then move Y+2.597". I have a macro for this, and to move it back, but sometimes I want to overburn the sides of a project (e.g. canvas or tile), so I really want to place the material at X1" Y1" and move the machine to X0.95" Y2.547". Additionally, with overscanning settings in LightBurn, I almost never want the project piece placed at X0. 

Similarly, I sometimes have to manually jog to a new position if I want to cut into a project piece bigger than the original design.

--

In these cases, I can manually jog but if the position I want to go to isn't a perfect multiple of one of the the XY/Z move settings I have, then I have to get it as close as possible and change those settings then move it again, then change the settings back in order to get perfect positioning.

If there were a "Go To Position" button with a dialog that allowed you to choose either absolute or relative position and enter X, Y, and Z values, it would be very simple to type in the exact position I want the machine to go to without editing my XY/Z move settings and clicking the jog buttons a bunch of times.

**Comment by kglovern** [comment]
This is available as of Edge 1.3.0 and will go to main build along with the rest of the rotary changes.

![image](https://github.com/Sienci-Labs/gsender/assets/22222507/8da9cb95-4d3e-431b-a48c-2ec46dcc3188)

![image](https://github.com/Sienci-Labs/gsender/assets/22222507/33792542-1144-44b9-8077-a916e8492b31)
