### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by neilferreri** [Sienci-Labs/gsender#323]
What's the easiest way to build a custom installation of gSender to try out some things?

**Comment by kglovern** [comment]
Hi Neil,

If you're looking to build an executable,

yarn build
yarn build:{os} - For example, `yarn build:windows`

If you're just looking to have a dev build hosted locally, you can just use `yarn dev` and access it at localhost:8000.

Replace yarn with npm run depending on your local environment.

**Comment by petervanderwalt** [comment]
We’ve put together a new official guide that covers how to build gSender locally, along with solutions to the most common build and dependency issues on different platforms (Windows, macOS, Linux, Raspberry Pi, etc.).

You can find it here:
[Sienci Resources > gSender > Experiment > Compile gSender](https://resources.sienci.com/view/gs-compile/)

This page includes setup instructions, troubleshooting tips, etc. If your question was about building or compiling gSender, you should find everything you need there.

If you still have any errors after following the instructions, do let us know and we can look into your specific issues a little more

Thanks for your patience and for helping us improve the documentation, we are really looking forward to your contributions to gSender as well!
