### ISSUE TITLE
Outline click needs a hotkey

### ISSUE THREAD

**Issue by Windcrest77** [Sienci-Labs/gsender#368]
Would you please assign a hotkey to the Outline function. I couldnt find one in the list. I am programming a small macro keyboard to control my machine and I use the Outline function a lot to make sure my job wont clobber into one of my clamps when I run it for real. Having this keypress available while standing at the machine would be great instead of walking back to the screen.

I'll leave un-programmed button open on my keypad in the hope that you will add a hotkey for Outline in the near future.

**Comment by kglovern** [comment]
This will be available in the next release.
