### ISSUE TITLE
Bug - Hotkey report printer margin too small

### ISSUE THREAD

**Issue by Windcrest77** [Sienci-Labs/gsender#370]
I verified this with several printers, including a brand new Brother laser. When you print the hotkeys, the left text is truncated because it is printing outside the margin of most printers. Printing to PDF looks fine, but when you physically print on paper the left edge first letter is cut off each line.

Would you please leave a bigger left margin for the hotkey report. Maybe 3/4 inch should fix it.

**Comment by kglovern** [comment]
Should be a larger margin next release.
