### ISSUE TITLE
Bug - Unlock hotkey doesn't work when red lock alert is on screen

### ISSUE THREAD

**Issue by Windcrest77** [Sienci-Labs/gsender#371]
I programmed the Unlock hotkey as ctrl + e. But it doesnt send the unlock to the program when the screen has that red "Click to Unlock Machine" alert up. To reproduce the problem I do this....

I intentionally jog one of my axis up against a limit switch. This causes gSender to put up the lock alert. I manually move the axis off of the limit switch. When I use the mouse to click Unlock the machine unlocks just fine, the alert goes away. But if I do the very same steps as above, except using the mouse I use the ctrl + e hotkey... nothing happens. It's as though gSeneder has no hotkey mapping for the Unlock while that alert is showing on the screen. It should unlock the alert. All other hotkeys work, as well as ones I've assigned myself, but the Unlock hotkey isn't working.

![Screenshot 2023-06-22 112321](https://github.com/Sienci-Labs/gsender/assets/53095763/e987c2ff-d5fe-43e5-a424-653c208a1b33)

**Comment by kglovern** [comment]
Alarm 1 (hard limits, like you triggering a limit switch) requires a soft reset along with just an unlock.  Next release will do the same behaviour as the UI button and shortcut (alarms that also require soft resets will do so for shortcuts as well)
