### ISSUE TITLE
New Feature Request

### ISSUE THREAD

**Issue by purpleguyaccount** [Sienci-Labs/gsender#399]
Console also includes  line numbers
An input field to start from a line number.

Would be nice if you used mouse wheel to scroll back and forth in console that shows the bit in the visualization window
move and maybe another button that starts/resumes the carve from that position

**Comment by kglovern** [comment]
Start from line is already a feature, you can access it by clicking the dotted lines on the start job button.

![image](https://github.com/Sienci-Labs/gsender/assets/22222507/71cb6e0e-a463-4576-a17c-a7091fd5f626)

We can consider adding line numbers to console but it's generally noise compared to the job progress area.

Unlikely that we consider using the console as anything other than data wrt visualization when scrolling through history.
