### ISSUE TITLE
Override buttons should increment by 10% not 1% and very slow

### ISSUE THREAD

**Issue by Windcrest77** [Sienci-Labs/gsender#417]
The two most important buttons in any sender program are the feed override buttons, especially when cutting aluminum, or when you see poor chip rates in any material. These buttons are like your hands when you are pushing a hand router, drill, circular saw, etc, very important they control how fast your pushing it! Something happened in the last release where a click gave me 10% now became just 1%, also these buttons became very slow, about 5 seconds response time per click. While the machine is cutting 5 seconds can mess up a lot of material. Also the hotkeys stopped working for the up and down overrides, but the hotkey that jumps to 100% still works. Hoping you please fix up the override buttons in these regards.

**Comment by kglovern** [comment]
Rapid override is available both using the slider.  We've fixed the shortcuts for the next release.
