### ISSUE TITLE
EDGE - Gamepad Z jogging

### ISSUE THREAD

**Issue by aarsene** [Sienci-Labs/gsender#422]
With the EDGE 1.3.7 release when I configure a button on my gamepad for Z+ and Z- jogging the router plunges when the Z- button is pressed once. It does not stop after the set distance. This used to work fine in 1.2.2. When I click the Z+ button nothing happens.

Gamepad: Logitech Rumblepad 2
OS: Windows 10 Pro

I also tried this with an Xbox 360 gamepad with the same result. I have tried closing and re=starting gSender to make sure the setting would take effect.

I also set buttons for "precise", "normal" and "fast" jogging and these work as expected.

**Comment by kglovern** [comment]
These should be fixed in the next EDGE release.
