### ISSUE TITLE
Home button section not visible on start (GRBL) v.1.3.9

### ISSUE THREAD

**Issue by vazhure** [Sienci-Labs/gsender#433]
Home button section not visible on start.
It appears only i go to Firmware menu
![gSender 1 3 9-EDGE 12_7_2023 13_06_34](https://github.com/Sienci-Labs/gsender/assets/124382776/555d2093-a32c-4bba-8d46-92ca710f2a37)

![gSender 1 3 9-EDGE 12_7_2023 13_09_03](https://github.com/Sienci-Labs/gsender/assets/124382776/9a7155d4-ec33-4666-b119-c30ca006fa1c)

**Comment by kglovern** [comment]
Which controller are you running that you need to send a query status on connection?  If the "??" eeprom query isn't able to be sent on connection we're unable to determine whether or not to show the homing area.

**Comment by vazhure** [comment]
> Which controller are you running that you need to send a query status on connection? If the "??" eeprom query isn't able to be sent on connection we're unable to determine whether or not to show the homing area.

MKS DLC 32
