### ISSUE TITLE
Probe issue

### ISSUE THREAD

**Issue by Marty1109** [Sienci-Labs/gsender#437]
Probe throws a soft limit alarm for the z-axis.

**Comment by kglovern** [comment]
Z axis probe distance is configurable in settings.

**Comment by Marty1109** [comment]
@kglovern i have played around witht he z axis distance and it didnt do anything i believe i have it set to 1.5" 

the tool will touch the probe (initial hit) move up and then alarm out for a soft limit alarm.

**Comment by SienciLabs** [comment]
@Marty1109 what direction is the soft limit occurring in?

**Comment by Marty1109** [comment]
Got it figured out

Believe it has to do with machine travel limit and search limit interfering with each other
