### ISSUE TITLE
Feature Request: Suppress gcode comments in gcode sent to machines.

### ISSUE THREAD

**Issue by gsrunion** [Sienci-Labs/gsender#444]
As per https://community.carbide3d.com/t/so5-pro-inline-comment-firmware-issue/64097 there is a bug in the firmware for the Shapeoko 5 Pro that causes the machine to choke on inline gcode comments.

While that ultimately needs to be fixed on their end, forwarding gcode comments to machines serves no purpose. I am proposing a change in gsender that strips out any gcode comments as gcode is being sent to the machine.

**Comment by kglovern** [comment]
We'll take a look at this for the next couple of releases.

**Comment by gsrunion** [comment]
Awesome. Thanks. JavaScript isn’t my strong suite by I may take a stab at putting up a PR.

**Comment by hamanjam** [comment]
I actually edited my post processor to add more comments such as file path and date saved  If you have no use for comments, it may be easier to edit your post processor to strip them out if they cause issues with your controller.  Parsing comments can be difficult.  Is there a specific Shapeoko post processor that doesn't produce comments?

For the purpose of stripping before sending, you'd have to regex to stop anything between "(" and ")" which would be something similar to :

string.replace(/\([^()]*\)/g, '')  


Similar thread with examples this solution was taken from:

https://stackoverflow.com/questions/640001/how-can-i-remove-text-within-parentheses-with-a-regex

**Comment by gsrunion** [comment]
From what I understand the probing routines on the GSender side insert inline comments as well. https://github.com/Sienci-Labs/gsender/blob/d3c86520890b9580517c792977988382b91dffdf/src/server/controllers/Grbl/GrblController.js#L479 here is at least one example.

**Comment by gsrunion** [comment]
You have a few options if you pay for a pro version of Carbide Create. Otherwise you are stuck with the default. The do provide a tool to extract the gcode from their C3D files. But that is another step. The LightBurn folks are coming out with a CNC software. I have high hopes for that. If not I pony up to move from VCarve Desktop to pro to not be size limited.

**Comment by gsrunion** [comment]
https://github.com/Sienci-Labs/gsender/blob/d3c86520890b9580517c792977988382b91dffdf/src/server/controllers/Grbl/GrblController.js#L418

and 

https://github.com/Sienci-Labs/gsender/blob/d3c86520890b9580517c792977988382b91dffdf/src/server/controllers/Grblhal/GrblHalController.js#L381

Might be the regex I would be looking for and, perhaps, the right place to do this replacement.

**Comment by gsrunion** [comment]
https://github.com/Sienci-Labs/gsender/pull/448 I attempted the changes as per guidance found here. https://community.carbide3d.com/t/gsender-any-special-steps-to-use/72349/39

**Comment by kglovern** [comment]
This should be merged and part of 1.4.1 release.  Thanks everyone for the feedback/pull requests.
