### ISSUE TITLE
Edge 1.3.10 Job list duplicates some entries

### ISSUE THREAD

**Issue by hamanjam** [Sienci-Labs/gsender#449]
I just noticed that most of my jobs are duplicated in the job table.  At first I couldn't confirm if they are in fact duplicates but they are.  I can't find a pattern right off but it seems like about 75% of the jobs I run show twice.    Also curious if it's possible to reset this information. 

![job_list](https://github.com/Sienci-Labs/gsender/assets/45050113/b66cf6f7-f910-43e4-959f-cc5a57f0b0cb)

**Comment by kglovern** [comment]
We'll take a look - Are you running Verify/check job before the actual file?  Otherwise we'll see why it's getting sent twice.

We'll look at adding a way to clear history but that will be in a future update.

**Comment by kglovern** [comment]
1) Verify is counting as a completed job for the purposes of both maintenance reduction and job stats when it shouldn't (no machine movement)
2) Double jobs seem to be reducing time twice as well

**Comment by hamanjam** [comment]
I don't see the duplication in 1.4.3 (or previous 1.4.x versions)
