### ISSUE TITLE
gSender 1.3.10 EDGE Outline button can become non-responsive

### ISSUE THREAD

**Issue by kbulgrien** [Sienci-Labs/gsender#453]
To reproduce the issue:

+ Start gSender 1.3.10 EDGE.
+ Connect to the machine.
+ Home the machine.
+ Load a "significant" .gcode file.
   - A 1000 line file is not "significant" enough.
   - I triggered this issue with a 504KB file having marginally more than 26000 lines.
+ Click the **Outline Button**.
   - Upon clicking the **Outline Button**, a **(i) Generate outline for current file** notification appears.
+ Either click **[X]** on the notification, or let it disappear on its own.
+ Close the file.
+ Open another "significant" .gcode file.
   - I chose a 811KB file of 31611 lines.
+ Note that the **Outline** button does nothing.
+ Close gSender 1.3.10 EDGE.
+ Repeat the above procedure, but swap the two files.
   - This proves that both trigger the notification dialog.
   - The **Outine** button becomes unresponsive without respect to which file is loaded first.

**Comment by kglovern** [comment]
This is fixed upstream and will be part of the next release 👍
