### ISSUE TITLE
Gsender doesnt play well with lower resolutions.

### ISSUE THREAD

**Issue by J-eremy** [Sienci-Labs/gsender#485]
With version 1.4.3 a problem has appeared in the UI that did not exist in previous versions. At least not on v1.4.1

The laptop I use has a low resolution of 1366x768 and the adjusters for the move increments and speed along with the tabs to move between functions are not usable anymore.

The tabs not being usable is the real dealbreaker.

![image](https://github.com/Sienci-Labs/gsender/assets/934651/87a024b9-47fc-4f41-bbee-4c4df1901c48)

**Comment by J-eremy** [comment]
This issue seems to be resolved as of 1.4.4-RC1. I will leave this open for anyone having this issue until 1.4.4 goes release.
Thanks everyone!

**Comment by kglovern** [comment]
Yes, as mentioned we've already fixed it and it should be part of the next release 👍

**Comment by kglovern** [comment]
This is now released as of 1.4.4 👍
