### ISSUE TITLE
Randomly losing "Program Events" settings

### ISSUE THREAD

**Issue by hamanjam** [Sienci-Labs/gsender#488]
Currently using 1.4.3:

Still trying to track down how to troubleshoot but it seems that if I leave gSender open for an extended period, my start and stop settings are gone from the Program Events tab.  Not sure if anything else is gone but that's the only changes I've made to settings.  I can restore my last saved settings and it will be normal and randomly when I start a job, and my dist collection doesn't start, I realize the start/stop commands are gone for my IOT device.  

If I look at the .sender_rc file at that time, the settings are no longer there so I restore from my last backup and I'm able to restart the job until the next time

**Comment by kglovern** [comment]
Thanks - we'll take a look when we can but as far as I know this hasn't come up for other users so will likely be in the release after next at earliest.

**Comment by hamanjam** [comment]
It's hard to track for sure and no rush but I wanted to bring up the issue just in case someone else sees it.  It's been off and on since Edge 1.3.10 I believe.

**Comment by hamanjam** [comment]
Closing for now.  Will re-open if I have more
