### ISSUE TITLE
v.1.4.4 The machine continues to move in jog mode after the joystick button is released

### ISSUE THREAD

**Issue by vazhure** [Sienci-Labs/gsender#489]
Just tried v.1.4.4.... The machine continues to move in jog mode after the joystick button is released .
It's magic I don't spoil anything 😅

**Comment by J-eremy** [comment]
Something like this has happened to me also, but the machine wasn't actually moving. The UI got stuck thinking the machine was jogging and became completely unresponsive.

**Comment by Vicnoname** [comment]
Not only joystick but also with computer keyboard.
Example..press shift+>
But just tap the key quickly the axis will keep going.
If the key is held down for an extended amount of time then it will stop.
Happens will stop axis

**Comment by kglovern** [comment]
Should be fixed as of 1.4.5.
