### ISSUE TITLE
All the links to Linux builds are 404

### ISSUE THREAD

**Issue by TangoOversway** [Sienci-Labs/gsender#490]
I wanted to download gSender for a Raspberry Pi, but when I click on the link for that download (From the main page), I get a 404 error. Same with the arm link and the Intel link. (Although if you go through the company's website the Raspberry Pi download link does lead to the Intel download, which is not useable on a Pi.)

**Comment by kglovern** [comment]
Thanks - links on readme are updated, site will be updated when marketing team is able.
