### ISSUE TITLE
feature - disable job summary

### ISSUE THREAD

**Issue by gcormier** [Sienci-Labs/gsender#493]
When I'm batching a ton of coaster jobs that take about 45 seconds each, the job summary is one extra popup I don't need at the end of the program.

Would be great to have an option to disable job summary. Bonus points, maybe disable job summary when job is less then X minutes in duration (also configurable).

**Comment by hamanjam** [comment]
enable/disable the summary would be nice.  We can always see the job history if we need to look back at a job

**Comment by BaysideCustomTC** [comment]
+1 vote for the option to disable. The Run Length is visible at the bottom of the screen, and the new Job History & Stats shows everything that we might need.

**Comment by kglovern** [comment]
We'll see what we can do.

**Comment by J-eremy** [comment]
Currently the job summary isn't hard bound to any confirmation. You can click anywhere on the window to make it disappear. Essentially you can just pretend it doesn't exist right now.

**Comment by kglovern** [comment]
It's pretty painless to clear from the screen yeah, but we agree that some people might not be interested in ever seeing it.  We're adding a preference to disable this (on by default) in the next release.
