### ISSUE TITLE
Workspace changing to P1 after job completion

### ISSUE THREAD

**Issue by BaysideCustomTC** [Sienci-Labs/gsender#494]
I sometimes run jobs in separate workspaces, each with their own XYZ0 origins.

After running a job in a workspace other than G54 (P1) e.g. G58 (P5), the workspace is set back to P1. If not noticed / corrected, then unwanted results can occur. For example, after completing a job I often move the spindle back to XY0 / Z39 as I know that to be a safe space. Obviously in P1's workspace that may not be a safe space for P5, causing collisions with clamps or other pieces of material.

I would expect that the workspace remains as P5, rather than being changed back to P1.

Please note that this is not a 1.4.4 specific behaviour - it operates the same in v1.1.7 and earlier.

![G58 before](https://github.com/Sienci-Labs/gsender/assets/164841285/6187aeea-d42e-4ac8-8776-856886e44347)
![G54 after](https://github.com/Sienci-Labs/gsender/assets/164841285/2203f77b-f941-49af-af8c-ecf13b349225)

**Comment by hamanjam** [comment]
This is expected behavior.  The end of your file most likely has an M2 command.  See this link:

https://resources.sienci.com/view/gs-feedback/#workspace-is-changing-when-a-job-is-run

**Comment by BaysideCustomTC** [comment]
It does indeed have an M2 command, as I would have expected. I amended the Program Start & Program Stop Events per the article linked and the behaviour is now as I would like. Thanks @hamanjam
