### ISSUE TITLE
No toolchange prompt

### ISSUE THREAD

**Issue by gcormier** [Sienci-Labs/gsender#503]
1.4.6, Windows 11

I've done toolchanges before, not sure what has happened.

gsender sees the tools

![image](https://github.com/Sienci-Labs/gsender/assets/8388983/1b688332-a30a-450e-8a0a-718650426da2)

```
...
G1X35.135Y-128.676
G1X34.196Y-128.593
G0Z6.350
G0Z25.400
M5
M6 T150
S24000M3
G4P6
G0X15.848Y-110.007
G0Z6.350
...
```

You can see we are at the last XYZ before toolchange.

![image](https://github.com/Sienci-Labs/gsender/assets/8388983/d798bf21-1e4e-4ef5-8b98-dfd89db00d5a)oBut it's just Resume Job or Stop Job as an option.

When I ran the file, it did the proper toolchange sequence after hitting Start Job (probe initial, probe new, everything looks good).

**Comment by gcormier** [comment]
Config

![image](https://github.com/Sienci-Labs/gsender/assets/8388983/556e7790-41c1-43e2-834b-e26739b33549)

**Comment by gcormier** [comment]
[test_toolchange.txt](https://github.com/Sienci-Labs/gsender/files/14971844/test_toolchange.txt)

This file will repro the issue for me.

**Comment by kglovern** [comment]
Thanks, we'll take a look.

**Comment by kglovern** [comment]
This should be fixed in the next release.

**Comment by gcormier** [comment]
Any guesses which version this bug appeared in? Have a few multi tool jobs to run this weekend. I can downgrade until the next version. (Or is EDGE a nightly build?)

**Comment by gcormier** [comment]
1.4.4 seems OK
