### ISSUE TITLE
Feature Request - Resume Job / Power Outage

### ISSUE THREAD

**Issue by CybergNetwork** [Sienci-Labs/gsender#516]
Resume Job if there is a power outage. Same as found in 3D printers. Just a scripts that reads the gcode and remember where it was at. Even if was starting from a few lines above the line it was working on, it would be a time & resource saver.

Thank you and keep up the good work!

**Comment by kglovern** [comment]
We actually have start-from-line functionality already built into the software - documentation can be found here:

https://resources.sienci.com/view/gs-using-gsender/#job-loss-recovery

**Comment by CybergNetwork** [comment]
You guys thought about everything! lol Thank you for educating me. You can delete my post then.

Have a great day.


On Jun 3, 2024, at 07:18, Kevin Glover-Netherton ***@***.***> wrote:



We actually have start-from-line functionality already built into the software - documentation can be found here:

https://resources.sienci.com/view/gs-using-gsender/#job-loss-recovery
