### ISSUE TITLE
Feature request - maintenance warning on startup

### ISSUE THREAD

**Issue by hamanjam** [Sienci-Labs/gsender#519]
I love the maintenance schedule but when I'm on a roll, I forget to check elapsed hours.  I would like to request an optional alert on program startup when maintenance is due on any items in the schedule.  It would be sufficient to have an enable/disable toggle and when enabled, it would pop up a message (similar to the job complete) stating that maintenance items are due.

**Comment by kglovern** [comment]
You should be getting prompts for overdue tasks as of 1.4.8.
