### ISSUE TITLE
1.4.8 error1

### ISSUE THREAD

**Issue by hamanjam** [Sienci-Labs/gsender#526]
Getting error on Ethernet connect.  This happens with or without a file loaded.  I am able to dismiss the error and start a job

![image](https://github.com/user-attachments/assets/fe857d79-8683-432a-91da-29a09ccf597d)

**Comment by kglovern** [comment]
Thanks, should be fixed in next release 👍

**Comment by kglovern** [comment]
This should be fixed in 1.4.9, thanks for the report.
