### ISSUE TITLE
Minimal movement in X and Y.

### ISSUE THREAD

**Issue by scipio2427** [Sienci-Labs/gsender#531]
I am experiencing a problem in that the X and Y motion 
on my Vevor 3018 engraver only moves at a very slow speed in jogging mode, and when in the run mode, the spindle only moves about 3mm in each direction. I have tried new steppers and a replacement control board without success. I have uninstalled gsender and re-loaded with no change to this pattern. Any assistance would be appreciated, but in newby language please.

**Comment by kglovern** [comment]
If this is happening when running files, it's likely you need to adjust your travel resolution in your EEPROM or have some other hardware issues.  You'd need to check with your manufacturer to determine what your default values should be.

This is ultimately not a gSender issue, so we'll be closing this issue.
