### ISSUE TITLE
$G command not reporting for grblHAL

### ISSUE THREAD

**Issue by jgreilick** [Sienci-Labs/gsender#537]
I have found that when connecting to grblHAL firmware, `$G` from the console does not report the parser state. I have looked through the source code and believe I have found the issue. I have not built and tested, but this is what I found:

from - src/server/controllers/Grblhal/constants.js - Line 48

`GCODE_REPORT: '$G\n',` should be `GCODE_REPORT: '$G',` without the newline character. This newline character is inconsistent with similar constants defined here and with the corresponding equality check for `$G` that occurs in the GrblController (Line 2107).

**Comment by kglovern** [comment]
It's not the newline per se, it's that $G on grblHAL doesn't also include a 'OK' response where Vanilla grbl does.  We've adjust the parsers to account for this and it should be fixed in the next release.
