### ISSUE TITLE
change telnet port

### ISSUE THREAD

**Issue by RalfGebhard** [Sienci-Labs/gsender#538]
pls make standard telnet port 23 (grbl over network) changable.

Ralf.

**Comment by hamanjam** [comment]
It's in firmware  setting 305
![telnet](https://github.com/user-attachments/assets/a606aa7b-31c1-4bdb-b97a-33cb22b91739)

**Comment by walidkayhan** [comment]
This issue has not been commented on in a while, I'll be closing it for now.
