### ISSUE TITLE
The screen could use adjustment in a 16:9 aspect ration

### ISSUE THREAD

**Issue by tigeryell99** [Sienci-Labs/gsender#539]
When running gSender on a 16:9 aspect ratio monitor  the "Zero All", "GoTo" for the X, and the "Zero X" buttons overlap outline (picture attached), but more importantly the buttons at the bottom can disappear behind the Windows taskbar (which I do not have a picture of).
![gSenderBug](https://github.com/user-attachments/assets/75db6b97-6ff2-42ed-a564-001f68a02830)

**Comment by kglovern** [comment]
The next Edge cycle is focused on a UI refresh, which will address this.
