### ISSUE TITLE
Lightweight Mode

### ISSUE THREAD

**Issue by Heywrd43** [Sienci-Labs/gsender#54]
Just downloaded gSender v6.5 from GitHub and installed. Connected to LongMill controller no issues yet. Turned on Lightweight mode switch before loading a gcode file.  When turned on gSender acted like I had loaded a gcode file. The load file icon does not show a file (X) loaded but the "Test Run" and "Start Job" icons appear. I selected both and they switch to the "Pause" and "Stop" icons with no movement of the tool and the visualizer is blank. I have previously loaded a file as it shows in the "Previous" window. Also every once in testing it was posting values in the X, Y and Z (not zero) positions even though no file loaded. See pictures below. Picture 1 connecting to controller. Picture 2 after connecting to controller and selecting "Lightweight Mode".

![Before No Connect](https://user-images.githubusercontent.com/85418236/120908253-3f738100-c636-11eb-8de3-dfbd248887fc.jpg)

![After Connected](https://user-images.githubusercontent.com/85418236/120908256-47cbbc00-c636-11eb-835e-b6da4a9eb42f.jpg)

**Comment by kglovern** [comment]
Thanks for the report,

We've addressed the play/test buttons appearing with no file loaded in the next build - it should be fixed in releases greater than 0.6.6.
