### ISSUE TITLE
settings disabled during alarm state

### ISSUE THREAD

**Issue by tcurdt** [Sienci-Labs/gsender#550]
I have a fresh grblHAL flash that gives an Alarm(10).
This is because I have to configure the inputs.

But the machines locked. Unlocking just gives

```
ok
client \x18
client $X
```

on the console and does not actually work.

The firmware settings are disabled.

Now this raises two questions:
1. why are the firmware settings disabled during an alarm
2. why can't I unlock the machine?

**Comment by tcurdt** [comment]
This is with 1.4.9 on macOS

**Comment by SienciLabs** [comment]
@kglovern I think this is down to how we handle Alarm state in gSender which make settings not available in Alarm state? I checked in ioSender and it seems possible to make this change, but not in gSender

**Comment by kglovern** [comment]
1.4.11 lets users use the firmware tool during alarm states.
