### ISSUE TITLE
newby

### ISSUE THREAD

**Issue by nspectorman** [Sienci-Labs/gsender#556]
Just got new Longmil 12x30, using windows 10 with g sender, I can jog in all directions  I can zero all axis, but when I try to run a test file the outline works, the verify works but the z axis does not come down far enough to even carve and suggestions.

**Comment by kglovern** [comment]
I'd look at making sure your Z zero is set correctly in both the CAM software and within gSender.  

Generally, this is not a public support forum for troubleshooting basic CNC use - I'd recommend asking on the Sienci community forum or submitting a ticket through Sienci customer support.
