### ISSUE TITLE
WEBGL problem on older computers

### ISSUE THREAD

**Issue by lappa1** [Sienci-Labs/gsender#561]
gSender reports a WEBGL problem. No other programs have problems.
Laptop is 12 years old with Intel Graphics 9000 onboard and NVIDIA GT540M card and drivers are up to date but gSender rejects them apparently.
Is there a work around for older computers?

**Comment by SienciLabs** [comment]
@lappa1 thanks for reporting your workaround. We don't have any other solutions to this currently so for now I'll link to your post for others to reference: https://forum.sienci.com/t/gsender-and-webgl/14136/
