### ISSUE TITLE
v1.5.0-Edge-1 DRO reports inconsistently

### ISSUE THREAD

**Issue by hamanjam** [Sienci-Labs/gsender#565]
When moving to XY0, DRO visualization shows X0.00, Z0.00 buy Y shows as -0.00  Minor issue but could be cause for confusion

![Screenshot 2024-10-21 134843](https://github.com/user-attachments/assets/0afbd398-bf3f-4441-9ea2-f2a0404af68e)

**Comment by kglovern** [comment]
This should be addressed in the next Edge release.
