### ISSUE TITLE
Passthrough value are not properly retrieve. 

### ISSUE THREAD

**Issue by siganberg** [Sienci-Labs/gsender#577]
Passthrough value are always evaluated to `false` even if you turn it ON unless user visited the Preference > Tool Change page.  

This might just not be isolated to Passthrough value but more likely the whole Preference object or `preference.toolChange` object.

https://github.com/Sienci-Labs/gsender/blob/909310474cfdca8d681ba1f3c0cd22f44ebda7da/src/server/controllers/Grblhal/GrblHalController.js#L505

How to replicate. 

* Go to the Preference > Tool Change  then tick the Passthrough switch to ON. 
* Close the gSender and open it again. 
* Now all the code that use this flag will always evaluated to false until user visit the Preference > Tool Change even without changing anything.

Tested in:

MacOS
Visual Code

**Comment by kglovern** [comment]
We made some alteration on the latest version to avoid this - passthrough value is correctly sent to backend on connect and file load alone with preferences change now.
