### ISSUE TITLE
Console Window

### ISSUE THREAD

**Issue by Jelga01** [Sienci-Labs/gsender#61]
(Win10 Laptop): Bottom text line and vertical scroll bar hidden under horizontal scroll bar. (why is there a horizontal scroll bar?)
(Win7 Laptop): Works better on my Win7 Laptop. On Win7 laptop there is no horizontal scroll bar but the bottom of the vertical scrollbar is still out of the window and hidden.  (must have plenty of text in window log to see this issue)
![scroll](https://user-images.githubusercontent.com/87214080/125150019-96271b80-e10a-11eb-837c-11d7735cce87.jpg)

**Comment by kglovern** [comment]
This should be resolved in the latest version - closing this issue for now
