### ISSUE TITLE
Control over color palette

### ISSUE THREAD

**Issue by cdo1955** [Sienci-Labs/gsender#65]
Is there a way to give the customer control over the colors used in the display area. I would like to be able to select the colors of the cut lines, lead in and lead outs etc. The colors that exist are very low contrast and hard to distinguish. UGS has this feature where you can customize the background, grid and path line colors to your liking. The dark or light  settings that are there give some control but not individual control over each color.
Overall I am very much liking the product, I would just like to tweak its appearance to my preferences.
 Thanks

**Comment by kglovern** [comment]
We're looking at adding more customization for the visualizer specifically at a future date, but it's somewhat on the backburnera s far as features go.  I'll ping again when we get this released.
