### ISSUE TITLE
Z- Crash version 0.7.3 and 0.7.4

### ISSUE THREAD

**Issue by tweathers-sec** [Sienci-Labs/gsender#66]
On two separate occasions when single-clicking Z-, the "Z move (mm)" was ignored and my spindle crashed into my spoil board requiring a hardware emergency stop interjection. This occurred at both Normal and Precise speeds.  Environment variables:

- OS = BigSur
- GRBL = Longmill build Sept 8, 2021
- gSender = v0.7.3 & 0.7.4
- Machine = CNC4Newbie, New-Carve 4510
- Controller = Demon Controller (Arduino UNO)
- Keyboard = Logitech K400 Wireless Keyboard

**Comment by kglovern** [comment]
We'll have some fixes in an upcoming build to address this.  There was an edge case where the jog cancel command wasn't correctly being sent if multiple continuous jogs were done in a row.
