### ISSUE TITLE
FeedRate Override overflow

### ISSUE THREAD

**Issue by neilferreri** [Sienci-Labs/gsender#69]
If the feedrate reaches its maximum override (255% in default LongMill?), another click of the increase will bring the feedrate down to just over zero.  The same happens in reverse
![feedRate_Issue](https://user-images.githubusercontent.com/2966894/143371362-e6b2aade-477b-4c4b-b371-6c795695dace.gif)
.

**Comment by kglovern** [comment]
Following up on this - this is related to a change someone made to the config.h on our latest GRBL firmware release.  They set the max override to 400, not realising the max possible value was 255.  It was 200 in previous versions.  As such, it's possible to overflow the 8 bytes.  In the meantime, we've added soft limits sender-side to reduce the chance of overflowing.  We will be releasing a new firmware version eventually to fix the config.  Thanks for the report!
