### ISSUE TITLE
Variable list?

### ISSUE THREAD

**Issue by gcormier** [Sienci-Labs/gsender#70]
Where can one find the list of variables available in a macro?

**Comment by SienciLabs** [comment]
Macros now have a drop-down of example variables available for use so feel free to check them out.

For more in-depth reading about the Macro Variables available, feel free to also check out the code supported by the library we use ([https://esprima.org/](https://esprima.org/)) and some of their documentation available here: [https://docs.esprima.org/en/latest/syntactic-analysis.html](https://docs.esprima.org/en/latest/syntactic-analysis.html). An example of more advanced variable usage could be using JS Math functions to perform trigonometry on-the-fly in an intricate probing cycle, see: [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math). Another example is using ternary expressions to choose between two outcomes (e.g. `%value=(30 > 20) ? 10 : 20` and then printing or using that value later on `([value])` or `G0 X[value])`.
