### ISSUE TITLE
Keyboard input on Windows versions of gSender 1.0.1 breaks application

### ISSUE THREAD

**Issue by tweathers-sec** [Sienci-Labs/gsender#72]
Tested on fresh installs of Windows 10 & 11 with x86 and x64 variants of gSender 1.0.1.

https://user-images.githubusercontent.com/59842250/144452531-35a9e12b-4cb4-4dc8-a305-6e1ca0cd74d0.mp4

**Comment by kglovern** [comment]
This was related to an issue with probe migrations and a new incoming probe profile and should be fixed with the build releasing later today.
