### ISSUE TITLE
Alarm 98 -When homing my cnc

### ISSUE THREAD

**Issue by angelperezleon** [Sienci-Labs/gsender#80]
Hi,
What does an "Alarm 98" mean?
I get this when trying to move my Z-axis +/- direction or even homing.

**Comment by SienciLabs** [comment]
@angelperezleon GRBL only has Alarms from 1 to 9 so an Alarm 98  shouldn't exist. Can you provide some more information perhaps with a picture or screenshot so we can help further with your issue?
