### ISSUE TITLE
1.0.6 Missing 32bit armv7I.deb build

### ISSUE THREAD

**Issue by Dakyleman** [Sienci-Labs/gsender#87]
It looks like the latest 1.0.6 release is missing the build for 32 bit Raspberry Pi (gSender_1.0.6_armv7I.deb). The links for the latest Pi build are pointing to this release but the links are dead, as the file does not seem to exist.

Thanks!

**Comment by kglovern** [comment]
Thanks for the report - We've run into an issue with the build process silently failing on the Pi.  Binaries for 1.0.7 will be made available Monday at the latest..
